name: Flask App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow-dispatch:  

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y default-libmysqlclient-dev gcc pkg-config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..20}; do
            if mysql -h 127.0.0.1 -P 3306 -uroot -prootpassword -e "SELECT 1;" > /dev/null 2>&1; then
              echo "MySQL is up!"
              break
            fi
            sleep 5
          done

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=supersecret" >> $GITHUB_ENV
          echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpassword" >> $GITHUB_ENV
          echo "DB_NAME=mydatabase" >> $GITHUB_ENV

      - name: Run tests (Flask starts & DB connection)
        run: |
          python -m flask --version
          python app.py &
          sleep 10
          curl http://127.0.0.1:5000/register || exit 1
