name: Setup Self-Hosted Runner on EC2

on:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and install GitHub Actions Runner
        run: |
          echo "$EC2_SSH_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > ec2.key.pem
          chmod 600 ec2.key.pem

          ssh -i ec2.key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            sudo mkdir -p /actions-runner && cd /actions-runner
            curl -o actions-runner-linux-x64.tar.gz -L https://github.com/actions/runner/releases/download/v2.320.0/actions-runner-linux-x64-2.320.0.tar.gz
            tar xzf ./actions-runner-linux-x64.tar.gz

            ./config.sh --url https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME \
                        --token YOUR_RUNNER_TOKEN \
                        --unattended --replace

            ./run.sh &
          EOF
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ubuntu # or ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
